- deps.edn
When the runtime environment of the project is not required,
`:replace-deps` is the recommended argument.
https://clojure.org/reference/deps_and_cli#_replace_project_environment_tool
> The `:replace-deps` arg has replaced `:extra-deps` for many tools

- deps.edn
hi John,
when trying your config, I found a compile error when trying to use `inspect/reveal-nrepl` (though for some reason, `inspect/reveal` worked just fine). It seems like the version of reveal currently in the config is outdated, and bumping to the latest reveal solves this issue.
Thanks for this nice config!
> Bump reveal to .154

- deps.edn
I tested this with JDK 8 builds from Oracle, OpenJDK, Zulu and AdoptOpenJDK and the only one I managed to get it work with was OracleJDK 8.
> Add more detail to REBL usage instructions

- deps.edn
A user.clj or data_readers.clj on the project path might affect the operation of the tool unless the project's paths are overridden. See also: https://ask.clojure.org/index.php/9857/could-option-that-variant-sdeps-avoid-having-specify-alias?show=9884#a9884
> Add replace-paths to aliases using replace-deps

- README.md
Certain tables were not displaying properly due to a `+` being used for the header separator row. I changed it to `|` which corrects the problem.
> Change + to | to fix table display issues

- deps.edn
This adds the `:security/nvd` alias (and a new Security section) to  `deps.edn`.
See https://github.com/rm-hull/nvd-clojure.
> Add :security/nvd alias

- deps.edn
* Let Eastwood source paths be inferred
* Rationale explained inline
* clj-kondo: also lint `"test"`
* seems a safer default?
> Let Eastwood source paths be inferred

- README.md
- deps.edn
Another quick one, adds the `:lint/cljfmt` target to find/fix formatting issues.
> Add :lint/cljfmt

- .github/workflows/super-linter.yml
Env Vars `VALIDATE_` language name specified will run, any languages not
specified are disabled
Regex should include the root directory and be passed to the clj-kondo command
hopefully
> github action: specify linters and regex for path to lint

- .github/workflows/manual-mega-linter.yaml
Created github actions workflow from mega-linter example, removing unwanted sections
https://raw.githubusercontent.com/nvuillam/mega-linter/master/TEMPLATES/mega-linter.yml
Added specific linters from super-linter configuration
The node.js assisted install tool failed part way through and did not generate a GitHub actions worflow file
> github-actions: mega-linter for markdown, yaml and deps.edn

- README.md
- deps.edn
See #31 for reasons and discussion.
This PR completely removes the alias and the documentation.  _EDIT: refactored to mark the `:security/nvd` alias as deprecated as there is potential for false positives from the clojure-nvd library being included on the classpath_
> Remove the recently added nvd alias

- README.md
```
$ clojure -M:lint/kondo
WARNING: Specified aliases are undeclared and are not being used: [:lint/kondo]
```
https://github.com/practicalli/clojure-deps-edn/blob/live/deps.edn#L905
> Fix a typo and name of the clj-kondo alias in readme

- deps.edn
> Update comments referencing `:project/outdated`

- README.md
Just a small typo noticed while setting up. Thanks for the incredible resources.
> Fix small typo (starup -> startup)

- .github/linters/markdown-lint.yml
- .github/linters/mega-linter.yml
- .github/workflows/megalinter.yaml
- CHANGELOG.org
- README.md
- deps-deprecated.edn
- deps.edn
Simplify the `deps.edn` configuration by moving alias definitions that are deprecated or unused to `deps-deprecated.edm`
Resolve #60 
- `:project/jar` & `:project/uberjar` - tools.build is recommended approach
- `:repl/cider` - covered by `repl/interactive` or `repl/rebel` (with rebel UI)
- `:format/cljfmt-check` and `:format/cljfmt-fix` - covered by `:format/cljfmt check | fix`
- `:test/kaocha`, `:test/kaocha-global`, `:test/kaocha-watch`, `:test/kaocha-cljs` - covered by `:test/run`, `:test/watch`
- `search/outdated` contains excludes added for the deprecated Congnitect REBL aliases
- `:repl/prepl` and `:repl/prepl-cljs`
- `:hack/antq` - used once to fix an issue in antq
- `repl/rebel-reveal`, `repl/rebel-reveal-light`, `inspect/reveal`, `inspect/reveal-light`, `inspect/reveal-local`, …
> Refactor aliases to simplify config

- CHANGELOG.org
- README.md
- deps-deprecated.edn
- deps.edn
sayid requires middleware to function correctly with Clojure CLI,
including the library as a dependency alone is not enough
Add the following alias definitions to support sayid
- `:repl/debug` run basic REPL prompt with sayid, and cider-nrepl middleware
- `:repl/debug-refactor` run basic REPL prompt with sayid, clj-refactor and cider-nrepl middleware
- `:repl/rebel-debug` run Rebel rich UI REPL prompt with sayid, and cider-nrepl middleware
- `:repl/rebel-debug-refactor` run Rebel rich UI REPL prompt with sayid, clj-refactor and cider-nrepl middleware
[Related: clojure-emacs/sayid/issues/35 & practicalli/spacemacs/issues/325]
[Resolve: #62]
> alias: sayid aliases that include middleware

- CHANGELOG.org
- deps.edn
📓 Description
Correct the test coverage alias name to `:test/coverage` 
:octocat Type of change
:beetle How Has This Been Tested?
:eyes Checklist
> alias: correct coverage alias name

- deps.edn
📓 Description
Changed the tag for io.github.seancorfield/deps-new to v0.6.0 to reflect the naming convention used on the project.
Resolve #80
:octocat: Type of change
:beetle: How Has This Been Tested?
:eyes: Checklist
> Update io.github.seancorfield/deps-new tag

- CHANGELOG.org
- deps.edn
📓 Description
This is the newest and simplest way of using FlowStorm. It requires you to swap your official Clojure compiler by ClojureStorm only at dev time.
https://flow-storm.github.io/flow-storm-debugger/user_guide.html#_clojurestorm
Also updates the existing FlowStorm alias - both version and github org.
:octocat: Type of change
:beetle: How Has This Been Tested?
:eyes: Checklist
> alias: add a lib/clojurestorm alias

- README.md
📓 Description
`:update` as an argument is silently ignored, the argument to update deps is `:upgrade`
https://github.com/liquidz/antq#clojure-cli-tools-11111139-or-later
:octocat: Type of change
:beetle: How Has This Been Tested?
:eyes: Checklist
> readme: correct upgrade argument for :search/outdated

- README.md
📓 Description
The --version option is the preferred way to do this and has existed long enough (since Feb 2021) that I don't think it's relevant to include the older command anymore.
An alternate approach would be to still include -Sdescribe as a fallback, but I really don't think that's necessary.
:octocat Type of change
:beetle How Has This Been Tested?
:eyes Checklist
> Update command to check Clojure CLI version

- README.md
📓 Description
:octocat Type of change
:beetle How Has This Been Tested?
:eyes Checklist
> Fix out of date task example
